// Turns a weekly summary into a written report in one of three voices.
//
// The text is composed from templates rather than generated by a language
// model: this app ships as static files with no backend and no API key, so
// there's nothing to call. Templates also make the output deterministic —
// the same week always reads the same way, and the tests can assert on it.
//
// Every persona reports the same facts. Only the framing changes.

export const COACHES = {
  mentor: 'The Mentor',
  drill_sergeant: 'The Drill Sergeant',
  analyst: 'The Analyst',
};

/**
 * What to work on, per category, in each voice. This is the part that has to
 * be specific — generic advice ("keep practising") is what makes a coach
 * sound like a form letter.
 */
const DIRECTION = {
  hanging_piece: {
    mentor:
      'try one small habit: before every move, pause and ask what your opponent could capture. It sounds almost too simple, but it clears up most of these on its own.',
    drill_sergeant:
      'check what your opponent can take before every single move, without exception — free pieces are not bad luck, they are inattention.',
    analyst:
      'Suggested intervention: a pre-move scan of opponent captures, which targets the dominant category directly.',
  },
  missed_tactic: {
    mentor:
      "a few minutes of tactics puzzles a day would go a long way — you're already reaching these positions, so it's about spotting the pattern, not finding new ideas.",
    drill_sergeant:
      'fifteen tactics puzzles a day weighted to forks, pins and skewers, because you keep reaching winning positions and walking straight past the win.',
    analyst:
      'Suggested intervention: daily tactics training weighted toward forks, pins and skewers.',
  },
  king_safety: {
    mentor:
      "try castling a little earlier than feels necessary. Giving your king a quiet corner early takes a whole class of problems off the table before they start.",
    drill_sergeant:
      'castle early and stop leaving your king in the middle. A king in the centre past move fifteen is an invitation, and your opponents keep accepting it.',
    analyst:
      'Suggested intervention: castle by move 12 where the position permits, reducing exposure in the middlegame.',
  },
  time_trouble: {
    mentor:
      "try spending your thinking time earlier in the game so you're not deciding the critical moments in a hurry. The moves were there — the clock just got in the way.",
    drill_sergeant:
      'manage the clock by deciding the easy moves fast and banking the time, because losing on quality after four minutes on move eight is a choice.',
    analyst:
      'Suggested intervention: redistribute clock usage toward the opening to preserve time for critical middlegame decisions.',
  },
  unclassified: {
    mentor:
      "it's worth playing back through your losses slowly. These slips didn't fall into a neat pattern, and often that just means the reason is worth finding by hand.",
    drill_sergeant:
      'sit down and review your own losses, because these errors did not fit a pattern and nobody is going to find them for you.',
    analyst:
      'Suggested intervention: manual review, as the errors did not match a recognised pattern.',
  },
};

const NOTHING_TO_REPORT = {
  mentor: (s) =>
    `No games analysed between ${s.from} and ${s.to}, so there's nothing to review yet. Play a few and I'll have something useful to tell you — a quiet ${periodNoun(s)} is not a bad one.`,
  drill_sergeant: (s) =>
    `No games between ${s.from} and ${s.to}. Nothing to review because you did not play. Get some games in.`,
  analyst: (s) =>
    `No games recorded between ${s.from} and ${s.to}. No blunder data available for this period.`,
};

const plural = (n, word) => `${n} ${word}${n === 1 ? '' : 's'}`;

// The window is usually a week but doesn't have to be, so the wording follows
// the data rather than assuming. Saying "this week" over a 30-day window is a
// small lie that undermines everything else in the report.
const isWeek = (s) => s.days === 7;
const periodPast = (s) => (isWeek(s) ? 'this week' : `over the last ${s.days} days`);
const periodNoun = (s) => (isWeek(s) ? 'week' : `${s.days} days`);
const mentorLead = (s) =>
  isWeek(s) ? 'For the week ahead' : `For the next ${s.days} days`;
const drillLead = (s) => (isWeek(s) ? 'This week:' : `Next ${s.days} days:`);

/** Grammar helper so sentences read naturally at 0, 1 and many. */
function blunderPhrase(count) {
  if (count === 0) return 'no blunders';
  return plural(count, 'blunder');
}

function mentorReport(s) {
  const lines = [];

  if (s.blunders === 0) {
    lines.push(
      `A clean ${periodNoun(s)} — ${plural(s.games, 'game')} analysed and not a single blunder among them. That's genuinely hard to do.`
    );
    lines.push(
      'Keep playing at this level and start pushing yourself against slightly stronger opposition; you can clearly handle it.'
    );
    return lines.join(' ');
  }

  lines.push(
    `You played ${plural(s.games, 'game')} ${periodPast(s)} and ${blunderPhrase(s.blunders)} turned up across them — that's ${s.blundersPerGame} a game, which is a very normal place to be.`
  );
  lines.push(
    `The pattern worth your attention is ${s.topCategoryLabel.toLowerCase()}: ${s.topCategoryCount} of the ${s.blunders} came from there, so it's the one area where progress will show up fastest.`
  );
  if (s.cleanGames > 0) {
    lines.push(
      `Worth noticing that ${plural(s.cleanGames, 'game')} came through completely clean, so you already know what it feels like when it goes right.`
    );
  }
  lines.push(
    `${mentorLead(s)}, ${DIRECTION[s.topCategory]?.mentor ?? DIRECTION.unclassified.mentor}`
  );
  return lines.join(' ');
}

function drillSergeantReport(s) {
  const lines = [];

  if (s.blunders === 0) {
    lines.push(`${plural(s.games, 'game')}, zero blunders — good.`);
    lines.push('Now play stronger opponents, because this lot are not testing you.');
    return lines.join(' ');
  }

  lines.push(
    `${plural(s.games, 'game')}, ${blunderPhrase(s.blunders)} — ${s.blundersPerGame} per game.`
  );
  lines.push(
    `${s.topCategoryCount} of them were ${s.topCategoryLabel.toLowerCase()}, and that is your problem.`
  );
  if (s.worstGame && s.worstGame.blunders > 1) {
    lines.push(
      `Your worst game gave away ${plural(s.worstGame.blunders, 'blunder')} against ${s.worstGame.opponent}, so go and look at it.`
    );
  }
  lines.push(
    `${drillLead(s)} ${DIRECTION[s.topCategory]?.drill_sergeant ?? DIRECTION.unclassified.drill_sergeant}`
  );
  return lines.join(' ');
}

function analystReport(s) {
  const lines = [];

  if (s.blunders === 0) {
    lines.push(
      `${plural(s.games, 'game')} analysed between ${s.from} and ${s.to}. Blunders: 0.`
    );
    lines.push('No category exceeded threshold. No corrective action indicated.');
    return lines.join(' ');
  }

  lines.push(
    `Period ${s.from} to ${s.to}: ${plural(s.games, 'game')}, ${plural(s.moves, 'move')}, ${blunderPhrase(s.blunders)} (${s.blundersPerGame} per game).`
  );
  lines.push(
    `Largest category: ${s.topCategoryLabel.toLowerCase()} at ${s.topCategoryCount} of ${s.blunders}, or ${Math.round(s.topCategoryShare * 100)}% of the total.`
  );
  lines.push(
    `Record ${s.record.win}-${s.record.loss}-${s.record.draw}; ${s.cleanGames} of ${s.games} games blunder-free.`
  );
  lines.push(DIRECTION[s.topCategory]?.analyst ?? DIRECTION.unclassified.analyst);
  return lines.join(' ');
}

const WRITERS = {
  mentor: mentorReport,
  drill_sergeant: drillSergeantReport,
  analyst: analystReport,
};

/**
 * Write the week up in one coach's voice.
 *
 * @param {'mentor'|'drill_sergeant'|'analyst'} coach
 * @param {object} summary  from summariseWeek()
 * @returns {string} 3-5 sentences
 */
export function writeReport(coach, summary) {
  if (!WRITERS[coach]) {
    throw new Error(
      `Unknown coach "${coach}". Options: ${Object.keys(WRITERS).join(', ')}`
    );
  }
  if (!summary || typeof summary.blunders !== 'number') {
    throw new Error('writeReport needs a summary from summariseWeek()');
  }

  if (summary.games === 0) return NOTHING_TO_REPORT[coach](summary);
  return WRITERS[coach](summary);
}

/**
 * One sentence for the home screen — the full report is too long to sit
 * above the fold on a phone, but the headline still has to be in voice.
 */
export function writeHeadline(coach, summary) {
  if (!WRITERS[coach]) throw new Error(`Unknown coach "${coach}"`);

  if (summary.games === 0) {
    return {
      mentor: 'No games yet in this stretch — play a few and I’ll have something for you.',
      drill_sergeant: 'No games logged. Nothing to work on until you play.',
      analyst: 'No games recorded for this period.',
    }[coach];
  }

  if (summary.blunders === 0) {
    return {
      mentor: 'Not a single blunder this time — that is genuinely hard to do.',
      drill_sergeant: 'Zero blunders. Good. Now find harder opponents.',
      analyst: 'Blunders: 0. No category exceeded threshold.',
    }[coach];
  }

  const label = summary.topCategoryLabel.toLowerCase();
  const pct = Math.round(summary.topCategoryShare * 100);

  return {
    mentor: `${summary.topCategoryCount} of your ${summary.blunders} blunders came from ${label} — that’s the one worth your attention.`,
    drill_sergeant: `${summary.topCategoryCount} of ${summary.blunders} were ${label}, so fix that before anything else.`,
    analyst: `${summary.topCategoryLabel} accounts for ${pct}% of blunders, the largest single category.`,
  }[coach];
}

/** All three voices for the same week, for side-by-side comparison. */
export function writeAllReports(summary) {
  return Object.fromEntries(
    Object.keys(WRITERS).map((coach) => [coach, writeReport(coach, summary)])
  );
}
