// The built-in recipe bank.
//
// It does three jobs:
//
//   1. It is the plan generator when no AI key is configured, so the whole
//      product — questionnaire, pricing, grocery list, swapping — works and
//      can be tested end to end without a network call.
//   2. It is the pool the budget optimiser pulls cheaper replacements from.
//   3. It is the swap menu's fallback when a model call fails.
//
// Every ingredient name here resolves through normalize.js to a food in
// foods.js. That is enforced by a test — an unmatched ingredient in the bank
// would silently become an unpriced line in someone's basket.
//
// Quantities are written for two servings and scaled from there.

const BASE_SERVINGS = 2;

/** [name, quantity, unit, optional?] → ingredient object. */
const ing = ([name, quantity, unit, optional]) => ({
  name,
  quantity,
  unit,
  optional: Boolean(optional),
});

function recipe(data) {
  const [calories, protein, carbs, fat] = data.nutrition;
  return {
    id: data.id,
    title: data.title,
    description: data.description,
    cuisine: data.cuisine,
    tags: data.tags ?? [],
    prepTimeMinutes: data.prep,
    cookTimeMinutes: data.cook,
    totalTimeMinutes: data.prep + data.cook,
    difficulty: data.difficulty ?? 'Easy',
    baseServings: BASE_SERVINGS,
    ingredients: data.ing.map(ing),
    instructions: data.steps,
    nutritionPerServing: { calories, proteinGrams: protein, carbGrams: carbs, fatGrams: fat },
    // Rough band, used to pick cheaper replacements before pricing runs.
    costTier: data.costTier ?? 'mid',
    source: 'bank',
  };
}

export const RECIPES = [
  recipe({
    id: 'chicken-burrito-bowls',
    title: 'Chicken Burrito Bowls',
    description: 'Seasoned chicken over rice with black beans, peppers and cheese.',
    cuisine: 'Mexican', tags: ['high-protein'], prep: 10, cook: 25, costTier: 'mid',
    ing: [['boneless chicken breast', 0.75, 'lb'], ['white rice', 1, 'cup'],
      ['black beans', 1, 'can'], ['bell pepper', 1, 'each'], ['yellow onion', 1, 'each'],
      ['shredded cheddar', 0.5, 'cup'], ['cumin', 1, 'tsp'], ['chili powder', 1, 'tsp'],
      ['lime', 1, 'each'], ['olive oil', 1, 'tbsp'], ['cilantro', 0.25, 'bunch', true]],
    steps: [
      'Cook the rice according to the package instructions.',
      'Toss the diced chicken with cumin, chili powder, salt and pepper.',
      'Sear the chicken in olive oil over medium-high heat until cooked through, 8–10 minutes.',
      'Add the sliced pepper and onion to the pan and cook until softened, 5 minutes.',
      'Warm the drained black beans, then build the bowls: rice, beans, chicken, vegetables.',
      'Top with cheese, a squeeze of lime and cilantro.',
    ],
    nutrition: [610, 44, 62, 19],
  }),
  recipe({
    id: 'chicken-quesadillas',
    title: 'Chicken and Pepper Quesadillas',
    description: 'Crisp tortillas filled with chicken, peppers and melted cheese.',
    cuisine: 'Mexican', tags: ['quick', 'high-protein'], prep: 10, cook: 15, costTier: 'low',
    ing: [['boneless chicken breast', 0.5, 'lb'], ['flour tortillas', 4, 'each'],
      ['shredded cheddar', 1, 'cup'], ['bell pepper', 1, 'each'], ['yellow onion', 0.5, 'each'],
      ['cumin', 1, 'tsp'], ['olive oil', 1, 'tbsp'], ['salsa', 0.5, 'cup', true]],
    steps: [
      'Slice the chicken thin and cook with cumin, salt and pepper until browned, 8 minutes.',
      'Add the sliced pepper and onion; cook until soft.',
      'Fill each tortilla with the mixture and cheese, then fold.',
      'Toast in a dry pan over medium heat until golden on both sides, about 2 minutes a side.',
      'Cut into wedges and serve with salsa.',
    ],
    nutrition: [640, 40, 51, 27],
  }),
  recipe({
    id: 'turkey-black-bean-chili',
    title: 'Turkey and Black Bean Chili',
    description: 'A one-pot chili that gets better the next day.',
    cuisine: 'American', tags: ['high-protein', 'leftovers'], prep: 10, cook: 35, costTier: 'low',
    ing: [['ground turkey', 1, 'lb'], ['black beans', 1, 'can'], ['kidney beans', 1, 'can'],
      ['diced tomatoes', 1, 'can'], ['yellow onion', 1, 'each'], ['bell pepper', 1, 'each'],
      ['garlic', 3, 'cloves'], ['chili powder', 2, 'tbsp'], ['cumin', 1, 'tbsp'],
      ['chicken broth', 1, 'cup'], ['olive oil', 1, 'tbsp'], ['shredded cheddar', 0.25, 'cup', true]],
    steps: [
      'Brown the turkey in a large pot over medium-high heat, breaking it up as it cooks.',
      'Add the diced onion, pepper and garlic; cook until softened, 5 minutes.',
      'Stir in the chili powder and cumin and cook for 1 minute until fragrant.',
      'Add the tomatoes, drained beans and broth. Simmer for 25 minutes, stirring now and then.',
      'Season to taste and top with cheese.',
    ],
    nutrition: [520, 42, 48, 17],
  }),
  recipe({
    id: 'crispy-chicken-wraps',
    title: 'Crispy Chicken Wraps',
    description: 'Panko chicken, crunchy cabbage and a quick yogurt sauce.',
    cuisine: 'American', tags: ['high-protein'], prep: 15, cook: 15, costTier: 'mid',
    ing: [['boneless chicken breast', 0.75, 'lb'], ['panko breadcrumbs', 1, 'cup'],
      ['large eggs', 1, 'each'], ['flour tortillas', 4, 'each'], ['green cabbage', 0.25, 'each'],
      ['plain greek yogurt', 0.5, 'cup'], ['lime', 1, 'each'], ['sriracha', 1, 'tbsp'],
      ['vegetable oil', 3, 'tbsp']],
    steps: [
      'Slice the chicken into strips, dip in beaten egg, then coat in panko.',
      'Fry in oil over medium heat until golden and cooked through, 3–4 minutes a side.',
      'Shred the cabbage and toss with lime juice and salt.',
      'Mix the yogurt with sriracha and a squeeze of lime.',
      'Fill the warm tortillas with chicken, slaw and sauce, then roll tightly.',
    ],
    nutrition: [660, 45, 55, 26],
  }),
  recipe({
    id: 'loaded-veg-rice-bowls',
    title: 'Loaded Vegetable Rice Bowls',
    description: 'Roasted vegetables and beans over rice with a lime-yogurt drizzle.',
    cuisine: 'American', tags: ['vegetarian', 'budget'], prep: 10, cook: 30, costTier: 'low',
    ing: [['white rice', 1, 'cup'], ['sweet potatoes', 1, 'lb'], ['bell pepper', 1, 'each'],
      ['red onion', 1, 'each'], ['black beans', 1, 'can'], ['plain greek yogurt', 0.5, 'cup'],
      ['lime', 1, 'each'], ['smoked paprika', 1, 'tsp'], ['cumin', 1, 'tsp'],
      ['olive oil', 2, 'tbsp'], ['cilantro', 0.25, 'bunch', true]],
    steps: [
      'Heat the oven to 425°F.',
      'Toss the cubed sweet potato, pepper and onion with oil, paprika, cumin and salt.',
      'Roast for 25–30 minutes, turning once, until browned at the edges.',
      'Cook the rice according to the package instructions.',
      'Warm the drained beans, then build the bowls and finish with lime-spiked yogurt.',
    ],
    nutrition: [540, 18, 88, 14],
  }),
  recipe({
    id: 'sheet-pan-chicken-veg',
    title: 'Sheet-Pan Chicken and Vegetables',
    description: 'One pan, twenty-five minutes, almost no washing up.',
    cuisine: 'American', tags: ['quick', 'high-protein', 'gluten-free'], prep: 10, cook: 25, costTier: 'mid',
    ing: [['boneless chicken thighs', 1, 'lb'], ['russet potatoes', 1, 'lb'],
      ['broccoli', 0.75, 'lb'], ['garlic', 3, 'cloves'], ['olive oil', 2, 'tbsp'],
      ['smoked paprika', 1, 'tsp'], ['italian seasoning', 1, 'tsp'], ['lemon', 1, 'each']],
    steps: [
      'Heat the oven to 425°F.',
      'Cut the potatoes small, toss with half the oil and seasoning, and roast for 10 minutes.',
      'Toss the chicken and broccoli with the rest of the oil, garlic and seasoning.',
      'Add to the pan and roast for 20–25 minutes, until the chicken reaches 165°F.',
      'Squeeze lemon over everything before serving.',
    ],
    nutrition: [580, 42, 44, 24],
  }),
  recipe({
    id: 'beef-taco-skillet',
    title: 'Beef Taco Skillet',
    description: 'Everything in a taco, in one pan, over rice.',
    cuisine: 'Mexican', tags: ['quick', 'high-protein'], prep: 5, cook: 20, costTier: 'mid',
    ing: [['ground beef', 1, 'lb'], ['white rice', 1, 'cup'], ['black beans', 1, 'can'],
      ['diced tomatoes', 1, 'can'], ['yellow onion', 1, 'each'], ['taco seasoning', 1, 'oz'],
      ['shredded cheddar', 0.5, 'cup'], ['romaine lettuce', 0.5, 'each', true]],
    steps: [
      'Cook the rice according to the package instructions.',
      'Brown the beef with the diced onion over medium-high heat, 8 minutes.',
      'Drain the fat, stir in the taco seasoning, tomatoes and drained beans.',
      'Simmer for 8 minutes until thickened.',
      'Serve over rice with cheese and shredded lettuce.',
    ],
    nutrition: [680, 40, 66, 26],
  }),
  recipe({
    id: 'spaghetti-meat-sauce',
    title: 'Spaghetti with Quick Meat Sauce',
    description: 'A weeknight ragù that tastes like it simmered all afternoon.',
    cuisine: 'Italian', tags: ['high-protein'], prep: 10, cook: 30, costTier: 'low',
    ing: [['spaghetti', 8, 'oz'], ['ground beef', 0.75, 'lb'], ['crushed tomatoes', 1, 'can'],
      ['yellow onion', 1, 'each'], ['garlic', 3, 'cloves'], ['tomato paste', 2, 'tbsp'],
      ['italian seasoning', 1, 'tbsp'], ['olive oil', 1, 'tbsp'], ['grated parmesan', 0.25, 'cup', true]],
    steps: [
      'Brown the beef with the diced onion in olive oil, 8 minutes.',
      'Add the garlic, tomato paste and Italian seasoning; cook for 2 minutes.',
      'Pour in the crushed tomatoes and simmer for 20 minutes.',
      'Meanwhile cook the spaghetti until al dente; reserve a little pasta water.',
      'Toss the pasta with the sauce, loosening with pasta water, and finish with parmesan.',
    ],
    nutrition: [700, 38, 82, 24],
  }),
  recipe({
    id: 'baked-ziti-veg',
    title: 'Baked Ziti with Spinach',
    description: 'Cheesy baked pasta with spinach folded through.',
    cuisine: 'Italian', tags: ['vegetarian'], prep: 10, cook: 35, costTier: 'low',
    ing: [['penne pasta', 8, 'oz'], ['crushed tomatoes', 1, 'can'], ['shredded mozzarella', 1.5, 'cup'],
      ['baby spinach', 5, 'oz'], ['garlic', 3, 'cloves'], ['yellow onion', 1, 'each'],
      ['italian seasoning', 1, 'tbsp'], ['olive oil', 1, 'tbsp'], ['grated parmesan', 0.25, 'cup', true]],
    steps: [
      'Heat the oven to 400°F and cook the pasta two minutes short of the package time.',
      'Soften the diced onion and garlic in oil, add the tomatoes and seasoning, simmer 10 minutes.',
      'Stir the spinach through until wilted, then fold in the drained pasta.',
      'Transfer to a baking dish, top with mozzarella and parmesan.',
      'Bake for 20 minutes until bubbling and browned on top.',
    ],
    nutrition: [640, 28, 84, 21],
  }),
  recipe({
    id: 'chicken-fried-rice',
    title: 'Chicken Fried Rice',
    description: 'The fastest way to turn leftover rice into dinner.',
    cuisine: 'Asian-inspired', tags: ['quick', 'high-protein'], prep: 10, cook: 15, costTier: 'low',
    ing: [['boneless chicken thighs', 0.75, 'lb'], ['white rice', 1, 'cup'],
      ['large eggs', 2, 'each'], ['frozen peas', 1, 'cup'], ['carrots', 1, 'each'],
      ['green onions', 3, 'each'], ['soy sauce', 3, 'tbsp'], ['toasted sesame oil', 1, 'tsp'],
      ['vegetable oil', 2, 'tbsp'], ['garlic', 2, 'cloves']],
    steps: [
      'Cook the rice ahead and cool it — day-old rice fries best.',
      'Sear the diced chicken in a very hot pan until browned, then set aside.',
      'Scramble the eggs in the same pan and set aside.',
      'Fry the diced carrot, garlic and peas for 3 minutes, then add the rice and press it flat.',
      'Return the chicken and egg, add soy sauce and sesame oil, and toss with the green onions.',
    ],
    nutrition: [620, 40, 66, 20],
  }),
  recipe({
    id: 'veg-stir-fry-tofu',
    title: 'Tofu and Vegetable Stir-Fry',
    description: 'Crisp tofu, a fast pan sauce and whatever vegetables you have.',
    cuisine: 'Asian-inspired', tags: ['vegetarian', 'vegan', 'quick'], prep: 10, cook: 20, costTier: 'low',
    ing: [['extra-firm tofu', 1, 'each'], ['frozen stir-fry vegetables', 1, 'lb'],
      ['white rice', 1, 'cup'], ['soy sauce', 3, 'tbsp'], ['rice vinegar', 1, 'tbsp'],
      ['honey', 1, 'tbsp'], ['cornstarch', 1, 'tbsp'], ['garlic', 3, 'cloves'],
      ['fresh ginger', 1, 'tbsp'], ['vegetable oil', 2, 'tbsp']],
    steps: [
      'Press the tofu dry, cube it and toss with cornstarch.',
      'Fry in hot oil until golden on all sides, 8 minutes, then set aside.',
      'Stir-fry the vegetables with the garlic and ginger for 5 minutes.',
      'Whisk the soy sauce, vinegar and honey with a splash of water, pour in and bubble to a glaze.',
      'Return the tofu, toss to coat, and serve over rice.',
    ],
    nutrition: [520, 24, 72, 16],
  }),
  recipe({
    id: 'lentil-curry',
    title: 'Red Lentil Curry',
    description: 'Creamy coconut lentils, ready in half an hour, cheap as anything.',
    cuisine: 'Indian-inspired', tags: ['vegetarian', 'vegan', 'budget', 'gluten-free'],
    prep: 10, cook: 25, costTier: 'low',
    ing: [['dry lentils', 1, 'cup'], ['coconut milk', 1, 'can'], ['diced tomatoes', 1, 'can'],
      ['yellow onion', 1, 'each'], ['garlic', 3, 'cloves'], ['fresh ginger', 1, 'tbsp'],
      ['curry powder', 1, 'tbsp'], ['ground turmeric', 1, 'tsp'], ['white rice', 1, 'cup'],
      ['vegetable oil', 1, 'tbsp'], ['cilantro', 0.25, 'bunch', true]],
    steps: [
      'Soften the diced onion in oil for 5 minutes, then add the garlic, ginger and spices.',
      'Add the rinsed lentils, tomatoes and coconut milk plus a cup of water.',
      'Simmer for 20–25 minutes until the lentils collapse, stirring occasionally.',
      'Cook the rice while the curry simmers.',
      'Season well and finish with cilantro.',
    ],
    nutrition: [610, 22, 88, 20],
  }),
  recipe({
    id: 'chickpea-shakshuka',
    title: 'Chickpea Shakshuka',
    description: 'Eggs poached in a spiced tomato and chickpea sauce.',
    cuisine: 'Mediterranean', tags: ['vegetarian', 'quick'], prep: 5, cook: 25, costTier: 'low',
    ing: [['chickpeas', 1, 'can'], ['crushed tomatoes', 1, 'can'], ['large eggs', 4, 'each'],
      ['yellow onion', 1, 'each'], ['bell pepper', 1, 'each'], ['garlic', 3, 'cloves'],
      ['cumin', 1, 'tsp'], ['smoked paprika', 1, 'tsp'], ['olive oil', 2, 'tbsp'],
      ['crumbled feta', 0.25, 'cup', true], ['sandwich bread', 4, 'slices', true]],
    steps: [
      'Soften the sliced onion and pepper in olive oil, 8 minutes.',
      'Add the garlic and spices, cook 1 minute, then add tomatoes and drained chickpeas.',
      'Simmer for 10 minutes until thickened, then season.',
      'Make four wells, crack in the eggs, cover and cook 6–8 minutes until the whites set.',
      'Scatter with feta and serve with bread for mopping.',
    ],
    nutrition: [520, 26, 52, 23],
  }),
  recipe({
    id: 'greek-chicken-bowls',
    title: 'Greek Chicken Bowls',
    description: 'Lemon-oregano chicken with couscous, cucumber and feta.',
    cuisine: 'Mediterranean', tags: ['high-protein'], prep: 15, cook: 20, costTier: 'mid',
    ing: [['boneless chicken breast', 0.75, 'lb'], ['couscous', 1, 'cup'], ['cucumber', 1, 'each'],
      ['cherry tomatoes', 1, 'cup'], ['red onion', 0.5, 'each'], ['crumbled feta', 0.5, 'cup'],
      ['plain greek yogurt', 0.5, 'cup'], ['lemon', 1, 'each'], ['dried oregano', 1, 'tbsp'],
      ['olive oil', 2, 'tbsp']],
    steps: [
      'Marinate the sliced chicken in lemon juice, oregano, oil, salt and pepper for 10 minutes.',
      'Cook the couscous according to the package instructions and fluff with a fork.',
      'Sear the chicken over medium-high heat until cooked through, 8 minutes.',
      'Chop the cucumber, tomatoes and onion into a quick salad.',
      'Build the bowls and top with feta and lemony yogurt.',
    ],
    nutrition: [620, 46, 56, 22],
  }),
  recipe({
    id: 'salmon-potatoes',
    title: 'Roast Salmon with Potatoes and Green Beans',
    description: 'A tray bake that feels like a proper dinner.',
    cuisine: 'American', tags: ['high-protein', 'gluten-free'], prep: 10, cook: 30, costTier: 'high',
    ing: [['salmon fillets', 0.75, 'lb'], ['russet potatoes', 1, 'lb'], ['green beans', 0.5, 'lb'],
      ['lemon', 1, 'each'], ['garlic', 3, 'cloves'], ['olive oil', 2, 'tbsp'],
      ['dried oregano', 1, 'tsp']],
    steps: [
      'Heat the oven to 425°F.',
      'Toss the halved baby potatoes with oil and salt; roast for 20 minutes.',
      'Add the green beans and garlic to the tray, and lay the salmon on top.',
      'Roast for another 10–12 minutes until the salmon flakes.',
      'Finish with lemon juice and oregano.',
    ],
    nutrition: [610, 40, 46, 27],
  }),
  recipe({
    id: 'fish-tacos',
    title: 'Crispy Fish Tacos',
    description: 'Spiced white fish with cabbage slaw and lime crema.',
    cuisine: 'Mexican', tags: ['quick'], prep: 15, cook: 15, costTier: 'mid',
    ing: [['tilapia fillets', 0.75, 'lb'], ['corn tortillas', 6, 'each'], ['green cabbage', 0.25, 'each'],
      ['plain greek yogurt', 0.5, 'cup'], ['lime', 2, 'each'], ['chili powder', 1, 'tsp'],
      ['cumin', 1, 'tsp'], ['vegetable oil', 2, 'tbsp'], ['cilantro', 0.25, 'bunch', true]],
    steps: [
      'Season the fish with chili powder, cumin and salt.',
      'Pan-fry in oil over medium-high heat, 3 minutes a side, then flake into large pieces.',
      'Shred the cabbage and dress with the juice of one lime and a pinch of salt.',
      'Stir the yogurt with the remaining lime juice.',
      'Warm the tortillas and build the tacos with fish, slaw, crema and cilantro.',
    ],
    nutrition: [520, 38, 46, 19],
  }),
  recipe({
    id: 'shrimp-scampi',
    title: 'Shrimp Scampi Pasta',
    description: 'Garlic, lemon and butter, tossed with spaghetti.',
    cuisine: 'Italian', tags: ['quick', 'high-protein'], prep: 10, cook: 15, costTier: 'high',
    ing: [['shrimp', 0.75, 'lb'], ['spaghetti', 8, 'oz'], ['garlic', 4, 'cloves'],
      ['butter', 3, 'tbsp'], ['lemon', 1, 'each'], ['crushed red pepper', 0.5, 'tsp'],
      ['olive oil', 1, 'tbsp'], ['flat-leaf parsley', 0.25, 'bunch', true]],
    steps: [
      'Cook the spaghetti until al dente and reserve a cup of pasta water.',
      'Sauté the sliced garlic in oil and butter over medium heat until fragrant, 1 minute.',
      'Add the shrimp and red pepper; cook 2 minutes a side until pink.',
      'Add lemon juice and a splash of pasta water to make a sauce.',
      'Toss with the pasta and parsley.',
    ],
    nutrition: [640, 42, 76, 19],
  }),
  recipe({
    id: 'pork-stir-fry',
    title: 'Ginger Pork Stir-Fry',
    description: 'Thin pork, crisp vegetables and a sticky ginger sauce.',
    cuisine: 'Asian-inspired', tags: ['quick', 'high-protein'], prep: 15, cook: 15, costTier: 'mid',
    ing: [['pork loin', 0.75, 'lb'], ['broccoli', 0.75, 'lb'], ['carrots', 2, 'each'],
      ['white rice', 1, 'cup'], ['soy sauce', 3, 'tbsp'], ['fresh ginger', 1, 'tbsp'],
      ['garlic', 3, 'cloves'], ['honey', 1, 'tbsp'], ['cornstarch', 1, 'tbsp'],
      ['vegetable oil', 2, 'tbsp']],
    steps: [
      'Slice the pork thin and toss with cornstarch and a spoon of soy sauce.',
      'Cook the rice according to the package instructions.',
      'Sear the pork in a hot pan until browned, 4 minutes, then set aside.',
      'Stir-fry the broccoli and sliced carrot with garlic and ginger for 5 minutes.',
      'Return the pork, add the remaining soy sauce and honey, and toss until glossy.',
    ],
    nutrition: [590, 40, 68, 16],
  }),
  recipe({
    id: 'sausage-peppers-pasta',
    title: 'Sausage and Peppers Pasta',
    description: 'Italian sausage, sweet peppers and a light tomato sauce.',
    cuisine: 'Italian', tags: ['high-protein'], prep: 10, cook: 25, costTier: 'mid',
    ing: [['italian sausage', 0.75, 'lb'], ['penne pasta', 8, 'oz'], ['bell pepper', 2, 'each'],
      ['yellow onion', 1, 'each'], ['crushed tomatoes', 1, 'can'], ['garlic', 3, 'cloves'],
      ['italian seasoning', 1, 'tsp'], ['olive oil', 1, 'tbsp'], ['grated parmesan', 0.25, 'cup', true]],
    steps: [
      'Brown the sausage in oil, breaking it into chunks, 8 minutes.',
      'Add the sliced peppers and onion; cook until softened, 8 minutes.',
      'Stir in the garlic, seasoning and tomatoes; simmer 10 minutes.',
      'Cook the pasta and toss it through the sauce.',
      'Finish with parmesan.',
    ],
    nutrition: [720, 34, 84, 27],
  }),
  recipe({
    id: 'stuffed-sweet-potatoes',
    title: 'Black Bean Stuffed Sweet Potatoes',
    description: 'Roasted sweet potatoes loaded with spiced beans and lime yogurt.',
    cuisine: 'American', tags: ['vegetarian', 'budget', 'gluten-free'], prep: 5, cook: 45, costTier: 'low',
    ing: [['sweet potatoes', 2, 'lb'], ['black beans', 1, 'can'], ['frozen corn', 1, 'cup'],
      ['plain greek yogurt', 0.5, 'cup'], ['lime', 1, 'each'], ['cumin', 1, 'tsp'],
      ['smoked paprika', 1, 'tsp'], ['shredded cheddar', 0.25, 'cup', true],
      ['green onions', 2, 'each', true]],
    steps: [
      'Heat the oven to 425°F and bake the pricked sweet potatoes for 45 minutes.',
      'Warm the drained beans and corn with the cumin and paprika.',
      'Stir the yogurt with lime juice and salt.',
      'Split the potatoes, fluff the insides and pile in the beans.',
      'Top with lime yogurt, cheese and green onions.',
    ],
    nutrition: [490, 18, 84, 10],
  }),
  recipe({
    id: 'egg-veg-hash',
    title: 'Potato, Pepper and Egg Hash',
    description: 'Crisp potatoes, soft peppers and eggs cooked right on top.',
    cuisine: 'American', tags: ['vegetarian', 'budget', 'gluten-free'], prep: 10, cook: 25, costTier: 'low',
    ing: [['russet potatoes', 1, 'lb'], ['bell pepper', 1, 'each'], ['yellow onion', 1, 'each'],
      ['large eggs', 4, 'each'], ['smoked paprika', 1, 'tsp'], ['olive oil', 2, 'tbsp'],
      ['shredded cheddar', 0.25, 'cup', true]],
    steps: [
      'Dice the potatoes small and fry in oil over medium heat, covered, for 12 minutes.',
      'Uncover, add the pepper and onion, and cook until everything is browned, 8 minutes.',
      'Season with paprika, salt and pepper.',
      'Make four wells, crack in the eggs, cover and cook until set, 5 minutes.',
      'Scatter with cheese and serve straight from the pan.',
    ],
    nutrition: [450, 20, 44, 22],
  }),
  recipe({
    id: 'chicken-noodle-soup',
    title: 'Chicken and Rice Soup',
    description: 'A pot of soup that stretches a pound of chicken a long way.',
    cuisine: 'American', tags: ['budget', 'leftovers', 'gluten-free'], prep: 10, cook: 30, costTier: 'low',
    ing: [['boneless chicken thighs', 0.75, 'lb'], ['chicken broth', 6, 'cups'],
      ['carrots', 3, 'each'], ['celery', 3, 'stalks'], ['yellow onion', 1, 'each'],
      ['white rice', 0.75, 'cup'], ['garlic', 3, 'cloves'], ['bay leaves', 2, 'each'],
      ['olive oil', 1, 'tbsp'], ['flat-leaf parsley', 0.25, 'bunch', true]],
    steps: [
      'Soften the diced carrot, celery and onion in oil for 8 minutes.',
      'Add the garlic and bay leaves, then the broth, and bring to a simmer.',
      'Add the chicken and poach for 15 minutes, then shred it and return it to the pot.',
      'Stir in the rice and simmer until tender, 15 minutes.',
      'Season generously and finish with parsley.',
    ],
    nutrition: [430, 34, 46, 12],
  }),
  recipe({
    id: 'tuna-white-bean-salad',
    title: 'Tuna and White Bean Salad',
    description: 'No cooking at all, on the table in ten minutes.',
    cuisine: 'Mediterranean', tags: ['quick', 'high-protein', 'no-cook'], prep: 10, cook: 0, costTier: 'low',
    ing: [['canned tuna', 2, 'cans'], ['cannellini beans', 1, 'can'], ['red onion', 0.5, 'each'],
      ['cherry tomatoes', 1, 'cup'], ['lemon', 1, 'each'], ['olive oil', 3, 'tbsp'],
      ['flat-leaf parsley', 0.25, 'bunch'], ['sandwich bread', 4, 'slices', true]],
    steps: [
      'Drain the tuna and beans and tip them into a bowl.',
      'Add the thinly sliced onion and halved tomatoes.',
      'Dress with lemon juice, olive oil, salt and plenty of black pepper.',
      'Fold through the chopped parsley and let it sit for 5 minutes.',
      'Serve with toast.',
    ],
    nutrition: [470, 38, 40, 18],
  }),
  recipe({
    id: 'chicken-parm-bake',
    title: 'Baked Chicken Parmesan',
    description: 'Crumbed chicken baked under tomato and mozzarella.',
    cuisine: 'Italian', tags: ['high-protein'], prep: 15, cook: 30, costTier: 'mid',
    ing: [['boneless chicken breast', 1, 'lb'], ['panko breadcrumbs', 1, 'cup'],
      ['large eggs', 1, 'each'], ['crushed tomatoes', 1, 'can'], ['shredded mozzarella', 1, 'cup'],
      ['grated parmesan', 0.25, 'cup'], ['garlic', 2, 'cloves'], ['italian seasoning', 1, 'tsp'],
      ['olive oil', 2, 'tbsp'], ['spaghetti', 8, 'oz', true]],
    steps: [
      'Heat the oven to 425°F.',
      'Dip the flattened chicken in beaten egg, then panko mixed with parmesan.',
      'Bake on an oiled tray for 18 minutes, turning once.',
      'Simmer the tomatoes with garlic and seasoning for 10 minutes.',
      'Spoon sauce over the chicken, top with mozzarella and bake 8 minutes more. Serve with pasta.',
    ],
    nutrition: [690, 52, 58, 25],
  }),
  recipe({
    id: 'veggie-chili-mac',
    title: 'Vegetarian Chili Mac',
    description: 'Chili and pasta in one pot, which is exactly as good as it sounds.',
    cuisine: 'American', tags: ['vegetarian', 'budget'], prep: 10, cook: 25, costTier: 'low',
    ing: [['penne pasta', 8, 'oz'], ['kidney beans', 1, 'can'], ['black beans', 1, 'can'],
      ['diced tomatoes', 1, 'can'], ['yellow onion', 1, 'each'], ['bell pepper', 1, 'each'],
      ['chili powder', 1, 'tbsp'], ['cumin', 1, 'tsp'], ['vegetable broth', 2, 'cups'],
      ['shredded cheddar', 0.5, 'cup'], ['olive oil', 1, 'tbsp']],
    steps: [
      'Soften the diced onion and pepper in oil for 5 minutes.',
      'Stir in the spices, then the tomatoes, drained beans and broth.',
      'Bring to a boil, add the dry pasta, and simmer for 12–14 minutes, stirring often.',
      'Season to taste — it should be saucy, not soupy.',
      'Stir half the cheese through and scatter the rest on top.',
    ],
    nutrition: [610, 26, 96, 14],
  }),
  recipe({
    id: 'turkey-burgers',
    title: 'Turkey Burgers with Slaw',
    description: 'Juicy turkey patties and a crunchy vinegar slaw.',
    cuisine: 'American', tags: ['quick', 'high-protein'], prep: 10, cook: 15, costTier: 'mid',
    ing: [['ground turkey', 1, 'lb'], ['burger buns', 4, 'each'], ['green cabbage', 0.25, 'each'],
      ['carrots', 1, 'each'], ['mayonnaise', 2, 'tbsp'], ['red wine vinegar', 1, 'tbsp'],
      ['garlic powder', 1, 'tsp'], ['smoked paprika', 1, 'tsp'], ['vegetable oil', 1, 'tbsp'],
      ['dijon mustard', 1, 'tbsp', true]],
    steps: [
      'Mix the turkey with the garlic powder, paprika, salt and pepper; form four patties.',
      'Cook in an oiled pan over medium heat, 5–6 minutes a side, until 165°F.',
      'Shred the cabbage and carrot; dress with mayonnaise and vinegar.',
      'Toast the buns in the pan.',
      'Build the burgers with slaw and mustard.',
    ],
    nutrition: [590, 40, 44, 26],
  }),
  recipe({
    id: 'mushroom-risotto-rice',
    title: 'Creamy Mushroom Rice',
    description: 'A risotto-adjacent skillet of rice, mushrooms and parmesan.',
    cuisine: 'Italian', tags: ['vegetarian'], prep: 10, cook: 30, costTier: 'low',
    ing: [['white rice', 1, 'cup'], ['white mushrooms', 16, 'oz'], ['yellow onion', 1, 'each'],
      ['garlic', 3, 'cloves'], ['vegetable broth', 3, 'cups'], ['grated parmesan', 0.5, 'cup'],
      ['butter', 2, 'tbsp'], ['olive oil', 1, 'tbsp'], ['flat-leaf parsley', 0.25, 'bunch', true]],
    steps: [
      'Brown the sliced mushrooms hard in oil, without crowding them, 8 minutes. Set aside.',
      'Soften the diced onion and garlic in butter, then add the rice and toast for 2 minutes.',
      'Add the broth a cup at a time, stirring, until the rice is tender, about 20 minutes.',
      'Fold the mushrooms and parmesan back in.',
      'Season well and finish with parsley.',
    ],
    nutrition: [520, 18, 74, 18],
  }),
  recipe({
    id: 'peanut-noodles',
    title: 'Peanut Noodles with Edamame',
    description: 'A cold-or-hot peanut sauce over noodles and greens.',
    cuisine: 'Asian-inspired', tags: ['vegetarian', 'quick'], prep: 10, cook: 15, costTier: 'low',
    ing: [['spaghetti', 8, 'oz'], ['peanut butter', 0.33, 'cup'], ['soy sauce', 2, 'tbsp'],
      ['rice vinegar', 1, 'tbsp'], ['honey', 1, 'tbsp'], ['garlic', 2, 'cloves'],
      ['frozen shelled edamame', 1, 'cup'], ['carrots', 2, 'each'], ['green onions', 3, 'each'],
      ['toasted sesame oil', 1, 'tsp']],
    steps: [
      'Cook the spaghetti, adding the edamame for the last 3 minutes.',
      'Whisk the peanut butter, soy sauce, vinegar, honey, garlic and sesame oil with hot pasta water.',
      'Drain the pasta and toss with the sauce.',
      'Fold through the grated carrot.',
      'Top with sliced green onion.',
    ],
    nutrition: [660, 26, 88, 24],
  }),
  recipe({
    id: 'bean-quesadillas',
    title: 'Black Bean and Cheese Quesadillas',
    description: 'The cheapest good dinner in the bank.',
    cuisine: 'Mexican', tags: ['vegetarian', 'budget', 'quick'], prep: 5, cook: 15, costTier: 'low',
    ing: [['black beans', 1, 'can'], ['flour tortillas', 4, 'each'], ['shredded cheddar', 1, 'cup'],
      ['yellow onion', 0.5, 'each'], ['cumin', 1, 'tsp'], ['chili powder', 1, 'tsp'],
      ['vegetable oil', 1, 'tbsp'], ['salsa', 0.5, 'cup', true]],
    steps: [
      'Soften the diced onion in oil, add the drained beans and spices, and mash roughly.',
      'Spread over half of each tortilla, top with cheese and fold.',
      'Toast in a dry pan, 2 minutes a side, until crisp.',
      'Rest for a minute so the cheese sets.',
      'Cut into wedges and serve with salsa.',
    ],
    nutrition: [560, 22, 66, 22],
  }),
  recipe({
    id: 'chicken-shawarma-bowls',
    title: 'Chicken Shawarma Bowls',
    description: 'Warm-spiced chicken over rice with cucumber and yogurt sauce.',
    cuisine: 'Mediterranean', tags: ['high-protein'], prep: 15, cook: 20, costTier: 'mid',
    ing: [['boneless chicken thighs', 1, 'lb'], ['white rice', 1, 'cup'], ['cucumber', 1, 'each'],
      ['roma tomatoes', 2, 'each'], ['red onion', 0.5, 'each'], ['plain greek yogurt', 0.5, 'cup'],
      ['lemon', 1, 'each'], ['cumin', 1, 'tsp'], ['smoked paprika', 1, 'tsp'],
      ['ground turmeric', 0.5, 'tsp'], ['garlic', 3, 'cloves'], ['olive oil', 2, 'tbsp']],
    steps: [
      'Toss the chicken with the spices, half the garlic, oil, lemon juice and salt.',
      'Cook the rice according to the package instructions.',
      'Sear the chicken over medium-high heat until charred at the edges and cooked through, 10 minutes.',
      'Mix the yogurt with the remaining garlic and lemon.',
      'Slice the chicken and serve over rice with chopped salad and sauce.',
    ],
    nutrition: [640, 44, 62, 22],
  }),
];

export const RECIPE_BY_ID = new Map(RECIPES.map((r) => [r.id, r]));

/** Every distinct cuisine, for the preferences screen. */
export const CUISINES = [...new Set(RECIPES.map((r) => r.cuisine))].sort();

/** Nutrition styles the questionnaire offers, and how each one scores a recipe. */
export const NUTRITION_STYLES = [
  {
    id: 'balanced',
    label: 'Balanced',
    blurb: 'A bit of everything across the week.',
    score: () => 0,
  },
  {
    id: 'high-protein',
    label: 'High protein',
    blurb: 'Protein forward in every dinner.',
    score: (r) => r.nutritionPerServing.proteinGrams / 10,
  },
  {
    id: 'vegetarian',
    label: 'Vegetarian',
    blurb: 'No meat or fish.',
    score: (r) => (r.tags.includes('vegetarian') ? 5 : -50),
  },
  {
    id: 'lower-calorie',
    label: 'Lower calorie',
    blurb: 'Lighter dinners, still filling.',
    score: (r) => (700 - r.nutritionPerServing.calories) / 50,
  },
  {
    id: 'budget-first',
    label: 'Budget first',
    blurb: 'Cheapest plan we can cook well.',
    score: (r) => ({ low: 4, mid: 1, high: -4 })[r.costTier] ?? 0,
  },
  {
    id: 'quick',
    label: 'Quick and easy',
    blurb: 'Nothing over about half an hour.',
    score: (r) => (45 - r.totalTimeMinutes) / 10,
  },
];

export const NUTRITION_BY_ID = new Map(NUTRITION_STYLES.map((style) => [style.id, style]));
